### ISSUE TITLE
API not working 

### ISSUE THREAD

**Issue by PascalOdudigbo** [chandan-02/anime-facts-rest-api#3]
![image](https://user-images.githubusercontent.com/69631521/176617940-b78d2ffd-1ea5-4291-bff6-728dad5e5d81.png)

I can't access resources anymore and i used this API for a project that's being graded today. Please help

**Comment by chandan-02** [comment]
> ![image](https://user-images.githubusercontent.com/69631521/176617940-b78d2ffd-1ea5-4291-bff6-728dad5e5d81.png)
> 
> I can't access resources anymore and i used this API for a project that's being graded today. Please help

**Comment by chandan-02** [comment]
My account was suspended by Heroku. :(

**Comment by PascalOdudigbo** [comment]
is there any way to resolve this?

**Comment by PascalOdudigbo** [comment]
Thank you so much
